[package]
name = "serder"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
der = "0.7.9"
serde = { version = "1.0.200", features = ["derive"] }
